CREATE TABLE users(
 id BIGINT NOT NULL AUTO_INCREMENT,
 username VARCHAR(40) NOT NULL UNIQUE,
 password VARCHAR(60) NOT NULL,
 email VARCHAR(60) NOT NULL UNIQUE,
 role VARCHAR(255) NOT NULL,
 PRIMARY KEY (id)
);